### ISSUE TITLE
TypeError: Cannot read property 'contextModuleFactory' of undefined

### ISSUE THREAD

**Issue by darlontrofy** [JLHwung/webpack-dll-ng-module-loader#2]
I tried using this package but got the error

compiler.hooks.contextModuleFactory.tap("cheat-angular-compiler-resource", function (cmf) {
                         ^
  TypeError: Cannot read property 'contextModuleFactory' of undefined

I followed all the instructions described. Can you help. I have asp.net core 2 with Angular 5 and have the dll plugin.

**Comment by JLHwung** [comment]
Hi darlontrofy,

What is your `webpack` version? Note that you can check by `npm ls webpack`.

If you are using `@angular/cli` 1.7, the `webpack` version is probably 3.x.

`webpack-dll-ng-module-loader` has not supported `webpack` 3 yet. It works well with webpack 4.

**Comment by JLHwung** [comment]
Closed since no reply in 1 month, feel free to reopen if you have further questions.
