### ISSUE TITLE
can not found modules after using webpack-dll-ng-module-loader plugin

### ISSUE THREAD

**Issue by digiwinSop** [JLHwung/webpack-dll-ng-module-loader#203]
can not found modules after using webpack-dll-ng-module-loader plugin

Error in my browser :

> sendSlackErrorMessage= Error: Uncaught (in promise): Error: Cannot find module './main/views/commons/commons.module'
> Error: Cannot find module './main/views/commons/commons.module'
>     at DllVendor.js:1673
>     at e.invoke (DllVendor.js:1879)
>     at Object.onInvoke (DllVendor.js:555)
>     at e.invoke (DllVendor.js:1879)
>     at t.run (DllVendor.js:1879)
>     at DllVendor.js:1879
>     at e.invokeTask (DllVendor.js:1879)
>     at Object.onInvokeTask (DllVendor.js:555)
>     at e.invokeTask (DllVendor.js:1879)
>     at t.runTask (DllVendor.js:1879)
>     at j (DllVendor.js:1879)
>     at j (DllVendor.js:1879)
>     at DllVendor.js:1879
>     at e.invokeTask (DllVendor.js:1879)
>     at Object.onInvokeTask (DllVendor.js:555)
>     at e.invokeTask (DllVendor.js:1879)
>     at t.runTask (DllVendor.js:1879)
>     at v (DllVendor.js:1879)
>     at t.invokeTask [as invoke] (DllVendor.js:1879)
>     at g (DllVendor.js:1902)
> 

and  this is the content in my app-routing.module.ts  (Using loadChildren)
```
path: 'main', component: MainComponent,
    children: [
      { path: '', redirectTo: 'home', pathMatch: 'full' },
      { path: 'home', component: HomeComponent, canActivate: [AuthGuard], data: { jobID: JOBID.GENERAL } },
      { path: 'setting', loadChildren: './main/views/setting/setting.module#SettingModule' },
      { path: 'report', loadChildren: './main/views/report/report.module#ReportModule' },
      { path: 'basic', loadChildren: './main/views/basic/basic.module#BasicModule' },
      { path: 'begin', loadChildren: './main/views/begin/begin.module#BeginModule' },
      { path: 'common', loadChildren: './main/views/commons/commons.module#CommonsModule' },
```
How can I fix this problem ?

**Comment by JLHwung** [comment]
@digiwinSop Could you attach your webpack config of building DLLVendor? We should make sure `webpack-dll-ng-module-loader` is _not_ bundled into a DLL.

**Comment by digiwinSop** [comment]
@JLHwung  thanks for the response.
For the purpose of testing, I didn't change the DllVendor session of the sample file you gave, 
 Therefore, the` webpack-dll-ng-module-loader` is not bundled into a DLL.

However, I had modified the `packson.json `  to append the` webpack-dll-ng-module-loader` to the devDependencies ( If I use `yarn add webpack-dll-ng-module-loader`, A NgModuleFactory not found error will occur while doing `npm start build`.
Therefore, I put the ` webpack-dll-ng-module-loader`  into `packson.json `   
and just execute `npm install ` and then `npm build:dll ` ; ` npm run build1` to build the dist using the plugin. 
As the result, the  modules that using the loadChildren command can not be found.
I attach some code of my project, Hope it helps.

Thanks. 
[A1Web_Angular2_webpack.zip](https://github.com/JLHwung/webpack-dll-ng-module-loader/files/3444983/A1Web_Angular2_webpack.zip)

**Comment by JLHwung** [comment]
@digiwinSop Hi, could you enable the following lines in the `app/app.module.ts` file of your attached project?
```
//import { WebpackDllNgModuleLoader } from "webpack-dll-ng-module-loader"
...
//{ provide: NgModuleFactoryLoader, useClass: WebpackDllNgModuleLoader },
```

**Comment by digiwinSop** [comment]
@JLHwung I am sorry that I forget to tell you, I remarked these two lines because a  `Cannot find name 'NgModuleFactoryLoader'.`  error occurred. This may be the actual causes of the problem of cannot found the modules.
However, I just confuse why has this happened?  
Do you think it is caused by the version difference of ng module?
or may cause by other reasons?

Very thanks for your help and patience. 
```

D:\Digiwin\A1Web_Angular2>npm run start1
npm WARN npm npm does not support Node.js v10.15.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> a1-web@0.0.0 start1 D:\Digiwin\A1Web_Angular2
> ng serve --plugin webpack-dll-ng-module-loader/ngx-build-plus --extraWebpackConfig ./webpack.partial.js

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 11% building 15/20 modules 5 active ...b\angular-calendar\angular-calendar.cssBrowserslist: caniuse-lite is outdated. Please run next command `npm update canius
Date: 2019-08-02T01:30:50.623Z
Hash: 284452e08ff600adb776
Time: 38285ms
chunk {main} main.js, main.js.map (main) 1.84 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 9.94 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1.26 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 288 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in src/app/app.module.ts(151,16): error TS2304: Cannot find name 'NgModuleFactoryLoader'.

```

**Comment by JLHwung** [comment]
> Cannot find name 'NgModuleFactoryLoader'

You have to 
```
import { NgModuleFactoryLoader } from "@angular/core"
```

It is a good question. I would update the docs so that people won't get confused here.

**Comment by digiwinSop** [comment]
Test OK, now. Thx for your help.

**Comment by digiwinSop** [comment]
@JLHwung  The project is running properly, now.
However, The build performance becomes slower than the original build speed(`npm run build`).
It takes a long time for building an AOT mode project.
Do you have any suggestion for my situation of building an AOT project?
Thx.

`D:\Digiwin\A1Web_Angular2>npm run build2
npm WARN npm npm does not support Node.js v10.15.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> a1-web@0.0.0 build2 D:\Digiwin\A1Web_Angular2
> node --max_old_space_size=4096 %~dp0/../node_modules/@angular/cli/bin/ng build --prod  --plugin webpack-dll-ng-module-loader/ngx-build-plus --extraWebpackConfig ./webpack.partial.js

 10% building 3/8 modules 5 active ...b\angular-calendar\angular-calendar.cssBrowserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-li
Date: 2019-08-04T07:21:53.870Z
Hash: a63ef0af19fe59c5bacd
Time: 609373ms
chunk {0} common.4d5fc3e5881d74a3070d.js (common) 22.5 kB  [rendered]
chunk {1} 1.bd4ded629fdde88fa9ec.js () 57.9 kB  [rendered]
chunk {2} 2.08f94c73aed6fbe2f185.js () 16.1 kB  [rendered]
chunk {3} 3.3cfbadb59f63c2c1ac71.js () 21.8 kB  [rendered]
chunk {4} 4.90c1d16204a6ac88e85b.js () 38.5 kB  [rendered]
chunk {5} 5.1966246f4f295c7b3e67.js () 69 kB  [rendered]
chunk {6} 6.03d15917898890d706e1.js () 156 kB  [rendered]
chunk {7} 7.ab2374215df13c2c7f87.js () 19.4 kB  [rendered]
chunk {8} 8.efe7cfa4ae878dc48ee8.js () 584 kB  [rendered]
chunk {9} 9.b573fcf02e77c1e4cf30.js () 199 kB  [rendered]
chunk {10} 10.ea093f13bf3604bf9c87.js () 16.2 kB  [rendered]
chunk {11} 11.4a2eb04aa2f0863f3821.js () 222 kB  [rendered]
chunk {12} 12.3e08f1003317407699dd.js () 233 kB  [rendered]
chunk {13} 13.1874e57c0865907635b9.js () 194 kB  [rendered]
chunk {14} runtime.f845d06df53fc8317b8a.js (runtime) 3.21 kB [entry] [rendered]
chunk {15} 15.99e288e8e755222d2ead.js () 2.11 MB  [rendered]
chunk {16} 16.86f6f01d7da37ce22099.js () 654 kB  [rendered]
chunk {17} 17.69d02e600325f64767dc.js () 341 kB  [rendered]
chunk {18} 18.df9ad462a407ecc460c8.js () 17.5 kB  [rendered]
chunk {19} 19.b16dc3d197118074e883.js () 16.7 kB  [rendered]
chunk {20} 20.329bcc68f87649b7b97d.js () 64.5 kB  [rendered]
chunk {21} 21.ed9c2b4b8cebeb5203ce.js () 17.3 kB  [rendered]
chunk {22} 22.198d2c64f5add12ea127.js () 118 kB  [rendered]
chunk {23} 23.a9500274e008d614d04e.js () 17.1 kB  [rendered]
chunk {24} 24.5fcdece5107940e04985.js () 90.6 kB  [rendered]
chunk {25} 25.980ca8b0e7e6a7c6b246.js () 188 kB  [rendered]
chunk {26} 26.7f48ab04ea145905465c.js () 89.4 kB  [rendered]
chunk {27} 27.6ac319ecaa05be92dd83.js () 4.81 kB  [rendered]
chunk {28} main.13f3a1b49eee2647559b.js (main) 1.95 MB [initial] [rendered]
chunk {29} polyfills.5921437a5a9dcebdccc1.js (polyfills) 9.02 kB [initial] [rendered]
chunk {30} styles.c0c912f275c6b7949c12.css (styles) 71.5 kB [initial] [rendered]
chunk {31} 31.383985b52bf8efedeaaa.js () 346 kB  [rendered]
chunk {32} 32.626a083863e4e477325c.js () 294 kB  [rendered]
chunk {33} 33.984dd96bd6f2b04582f7.js () 358 kB  [rendered]
chunk {34} 34.8b3f84d40c98aac78b41.js () 201 kB  [rendered]
chunk {35} 35.632f7cda8dfb7799e813.js () 61.3 kB  [rendered]
chunk {36} 36.bf7045cf1e60be7bfe23.js () 769 kB  [rendered]
chunk {37} 37.2ba2d9ff3812dcb97b54.js () 406 kB  [rendered]
chunk {38} 38.afeac1368dcd553e7568.js () 802 kB  [rendered]
chunk {39} 39.b2a49bdfe991e5ce8aa1.js () 1.04 MB  [rendered]
chunk {40} 40.a4481c6ecf587f9fb34e.js () 11 kB  [rendered]
chunk {41} 41.414db6e9c381524ef693.js () 218 kB  [rendered]
chunk {42} 42.dc0ceeb907e358e26414.js () 53.1 kB  [rendered]
chunk {43} 43.6d8d5bcb8d0fe83ff635.js () 224 kB  [rendered]
chunk {44} 44.98f51214e02cba6269f0.js () 86.2 kB  [rendered]
chunk {45} 45.231a92a83a6e40be8daa.js () 48 kB  [rendered]
chunk {46} 46.9a58802d985b58664bde.js () 11.2 kB  [rendered]
chunk {scripts} scripts.6918bfa4d1c2149cbad2.js (scripts) 876 kB [entry] [rendered]`

**Comment by JLHwung** [comment]
It is not recommended to apply AOT, a.k.a. Angular Compiler while you are using Webpack DLLs. Dll only works when you are using JIT compiler, where every module request, i.e. `import { fooComponent } from "bar" ` is _not_ changed. For example, when you are using Angular Compiler, the following code snippet
```ts
import { fooComponent } from "bar"
```
will be roughly changed to 
```ts
import * as bar from "bar";
import { ɵccf as createComponentFactory } from "@angular/core";
createComponentFactory(bar.fooComponentFactory);
```

By leveraging the private API, there is no way for a DLL build to include things like `ɵccf` into DLL builds. Therefore even if you got a dll plugged, the Angular Compiler will render it useless since it transforms public API calls to private API.

In all, if you are using Angular Compiler, I will bet DLL is a dead end.

**Comment by digiwinSop** [comment]
Thx for your explanation.
