### ISSUE TITLE
not worked in angular 7

### ISSUE THREAD

**Issue by jasonHzq** [JLHwung/webpack-dll-ng-module-loader#44]
I use ngx-build-plus to webpack。and use ng server to start my project. But it's not worked. All the NgModule not built.

**Comment by JLHwung** [comment]
Please provide a minimal reproduction repo otherwise it would be impossible to figure out what is going wrong.

**Comment by jasonHzq** [comment]
Well, So it's not a common problem. 

## My Code

I'm using ngx-build-plus and I start my project using angular-cli.

html code in my project only add dll vendor code. Others are provided witch angular cli. I think my problem are probably caused by this.

### html
```
<script src="dist/vendor/MyDll.vendor.js"></script>
<app-root></app-root>
```

## Error Stack

`Uncaught (in promise): Error: Cannot find module './app-home/index'
Error: Cannot find module './app-home/index'
    at MyDll.vendor.js:1719`

**Comment by JLHwung** [comment]
Glad to see you problems get solved. Feel free to reopen it if you have further issues.

**Comment by jasonHzq** [comment]
文档中：`If you are not bundling @angular/core to webpack dll, you probably never need this plugin.`。而这个 issue: `https://github.com/angular/angular-cli/issues/4565`。两者是否有矛盾？

**Comment by JLHwung** [comment]
I see there is no contradiction here. As is said in the header line

> Cheat AngularCompilerPlugin to work around `https://github.com/angular/angular-cli/issues/4565`

This library tries to fix this issue on the user land. Since the issue happens only when Angular is bundled to DLL files, and this practise is not supported by `@angular/cli`, so you will *not* need this library unless you use `@ngtools/webpack` + DLL configurations.

**Comment by jasonHzq** [comment]
Thanks for repling me so quickly, I will try to not use ngx-build-plus whereas @ngtools/webpack

**Comment by jasonHzq** [comment]
It's very important to our project, can I have a deep chat to u? Is there any way to contact with u?

**Comment by JLHwung** [comment]
> It's very important to our project

I can understand, so please draft a *reproduction repository*, otherwise I can not afford the time figuring out what happens in the roundtrip of mails.

**Comment by jasonHzq** [comment]
I have pushed my code in https://github.com/jasonHzq/ng-app

**Comment by JLHwung** [comment]
On first glimpse on the [webpack configuration](https://github.com/jasonHzq/ng-app/blob/master/webpack.config.js#L6), the `ngtools/webpack`, as well as AngularCompilerPlugin is absent. There is no way the app can be compiled.

You can check [the integration example](https://github.com/JLHwung/webpack-dll-ng-module-loader/tree/master/integration/example) here to see how to use this webpack loader.

**Comment by jasonHzq** [comment]
ngx-build-plus will auto merge the ngtools/webpack includes configuration of AngularCompilerPlugin! We can both use the feature of angular-cli and add some custom configuration which angular-cli not support. I also tried configuartion as the integration example, but also crashed.

**Comment by jasonHzq** [comment]
I think if the solution can only totally use webpack configuration，it will be too expensive, and lot's of features ng-cli provides cannot be used.

**Comment by jasonHzq** [comment]
Thanks! I ignore the note that the plugin must come before AngularCompilerPlugin!
